// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BXcuTZJH9O5zTZZExtRjqDO42Qeq8oM',
    appId: '1:319418037866:web:68db0daa3d327cf20afc13',
    messagingSenderId: '319418037866',
    projectId: 'livora-72675',
    authDomain: 'livora-72675.firebaseapp.com',
    storageBucket: 'livora-72675.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYMfH7Bml2Lm-DE0qCk3HP5e7WDhgm0g',
    appId: '1:319418037866:android:b4093d11ae4fb0490afc13',
    messagingSenderId: '319418037866',
    projectId: 'livora-72675',
    storageBucket: 'livora-72675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGit94C0EIWJiT_Hsv0J2Z_OlxH5uPN0',
    appId: '1:319418037866:ios:1a16fd8f9ed907530afc13',
    messagingSenderId: '319418037866',
    projectId: 'livora-72675',
    storageBucket: 'livora-72675.firebasestorage.app',
    iosBundleId: 'com.example.livora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeGit94C0EIWJiT_Hsv0J2Z_OlxH5uPN0',
    appId: '1:319418037866:ios:1a16fd8f9ed907530afc13',
    messagingSenderId: '319418037866',
    projectId: 'livora-72675',
    storageBucket: 'livora-72675.firebasestorage.app',
    iosBundleId: 'com.example.livora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6BXcuTZJH9O5zTZZExtRjqDO42Qeq8oM',
    appId: '1:319418037866:web:f0936d9a2bd0f11e0afc13',
    messagingSenderId: '319418037866',
    projectId: 'livora-72675',
    authDomain: 'livora-72675.firebaseapp.com',
    storageBucket: 'livora-72675.firebasestorage.app',
  );

}